Repository supsup-hae/11th-BE-Networking-May, pull requests merged in 2025-05, with the labels that each got.

#2 [Docs] 프로젝트 초기 설정 완료
  .github/ISSUE_TEMPLATE/bug-issue.md
  .github/ISSUE_TEMPLATE/issue.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: 📃 문서 (docs)

#5 [Deploy] 프로젝트 배포
  .github/workflows/docker_deploy.yml
  Dockerfile
  build.gradle
  src/main/java/cotato/backend/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: 🌏 배포 (deploy)

#8 [Feat] 공통 응답 및 전역 예외 처리 구현
  src/main/java/cotato/backend/global/common/ApiResponse.java
  src/main/java/cotato/backend/global/common/ErrorResponse.java
  src/main/java/cotato/backend/global/error/ErrorCode.java
  src/main/java/cotato/backend/global/error/GlobalExceptionHandler.java
  src/main/java/cotato/backend/global/error/exception/CustomException.java
  src/main/java/cotato/backend/global/error/exception/ExternalApiException.java
  src/main/java/cotato/backend/global/error/exception/ResourceNotFoundException.java
Labels: ✨ 기능 (feature)

#9 [Feat] 위치 서비스 개발 완료
  README.md
  build.gradle
  src/main/java/cotato/backend/api/location/LocationController.java
  src/main/java/cotato/backend/domain/location/converter/LocationConverter.java
  src/main/java/cotato/backend/domain/location/dto/request/LocationRequestDto.java
  src/main/java/cotato/backend/domain/location/dto/response/LocationResponseDto.java
  src/main/java/cotato/backend/domain/location/entity/Location.java
  src/main/java/cotato/backend/domain/location/exception/LocationException.java
  src/main/java/cotato/backend/domain/location/repository/LocationRepository.java
  src/main/java/cotato/backend/domain/location/service/command/LocationCommandService.java
  src/main/java/cotato/backend/domain/location/service/query/LocationQueryService.java
  src/main/java/cotato/backend/global/common/ErrorResponse.java
  src/main/java/cotato/backend/global/config/SwaggerConfig.java
  src/main/java/cotato/backend/global/entity/BaseEntity.java
  src/main/java/cotato/backend/global/error/ErrorCode.java
  src/main/java/cotato/backend/global/error/GlobalExceptionHandler.java
Labels: ✨ 기능 (feature), 📬 API (api)

#10 [Feat] 날씨 서비스 개발 완료
  .github/workflows/docker_deploy.yml
  src/main/java/cotato/backend/api/weather/WeatherController.java
  src/main/java/cotato/backend/domain/location/service/query/LocationQueryService.java
  src/main/java/cotato/backend/domain/weather/converter/WeatherConverter.java
  src/main/java/cotato/backend/domain/weather/dto/HourlyWeatherResponseDto.java
  src/main/java/cotato/backend/domain/weather/dto/WeatherDetailResponseDto.java
  src/main/java/cotato/backend/domain/weather/dto/WeeklyWeatherResponseDto.java
  src/main/java/cotato/backend/domain/weather/dto/Wind.java
  src/main/java/cotato/backend/domain/weather/enums/DustLevel.java
  src/main/java/cotato/backend/domain/weather/enums/UltraFineDustLevel.java
  src/main/java/cotato/backend/domain/weather/enums/UvIndexLevel.java
  src/main/java/cotato/backend/domain/weather/service/WeatherService.java
  src/main/java/cotato/backend/domain/weather/service/WeatherServiceImpl.java
  src/main/java/cotato/backend/global/config/RestTemplateConfig.java
  src/main/java/cotato/backend/global/config/SecurityConfig.java
  src/main/java/cotato/backend/infra/weather/FineDustClient.java
  src/main/java/cotato/backend/infra/weather/WeatherClient.java
  src/main/java/cotato/backend/infra/weather/dto/dust/DustApiResponseDto.java
  src/main/java/cotato/backend/infra/weather/dto/dust/DustResult.java
  src/main/java/cotato/backend/infra/weather/dto/openweather/DailyWeatherApiResponse.java
  src/main/java/cotato/backend/infra/weather/dto/openweather/HourlyWeatherApiResponse.java
  src/main/java/cotato/backend/infra/weather/dto/openweather/HourlyWeatherDto.java
  src/main/java/cotato/backend/infra/weather/dto/openweather/WeeklyWeatherApiResponse.java
  src/main/java/cotato/backend/infra/weather/dto/openweather/WeeklyWeatherDto.java
  src/main/java/cotato/backend/infra/weather/excpetion/WeatherException.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: ✨ 기능 (feature), 📬 API (api)

#13 [Feat] 날씨 인코딩 타입 변경 및 환경 변수 설정 변경
  .github/workflows/docker_deploy.yml
  src/main/java/cotato/backend/global/config/CorsConfig.java
  src/main/java/cotato/backend/infra/weather/WeatherClient.java
Labels: 🏷️ 작업필요 (help wanted)

#15 [Feat] 날씨 코드 변환 로직 추가 완료
  .github/workflows/docker_deploy.yml
  Dockerfile
  src/main/java/cotato/backend/domain/weather/converter/DescriptionConverter.java
  src/main/java/cotato/backend/domain/weather/converter/WeatherConverter.java
  src/main/java/cotato/backend/domain/weather/enums/WeatherCode.java
  src/main/java/cotato/backend/global/error/ErrorCode.java
  src/main/java/cotato/backend/infra/weather/WeatherClient.java
  src/main/resources/application.yml
Labels: ✨ 기능 (feature)

#16 [Feat] OpenWeather를 활용한 미세먼지 정보 추출 구현 완료
  src/main/java/cotato/backend/domain/weather/converter/WeatherConverter.java
  src/main/java/cotato/backend/infra/weather/FineDustClient.java
  src/main/java/cotato/backend/infra/weather/WeatherClient.java
  src/main/java/cotato/backend/infra/weather/dto/dust/DustApiResponseDto.java
  src/main/java/cotato/backend/infra/weather/dto/dust/DustResult.java
  src/main/java/cotato/backend/infra/weather/dto/openweather/AirPollutionData.java
  src/main/java/cotato/backend/infra/weather/dto/openweather/AirQualityIndex.java
  src/main/java/cotato/backend/infra/weather/dto/openweather/Components.java
  src/main/java/cotato/backend/infra/weather/dto/openweather/DustResult.java
  src/main/java/cotato/backend/infra/weather/dto/openweather/OpenWeatherMapAirPollutionResponse.java
Labels: 🏷️ 작업필요 (help wanted)
